#!/bin/bash

TEST_PUPIL_USERNAME=duguid.t TEST_PUPIL_PASSWORD=clover8556 \
TEST_TEACHER_USERNAME=t.duguid TEST_TEACHER_PASSWORD=clover8556 \
TEST_ADMIN_USERNAME=admin TEST_ADMIN_PASSWORD=ChangeMe123 \
npm run test:ui
